#!/usr/bin/env sh
# ------------------------------------------------------------
# Gradle start up script for UN*X
#
# Generated by the Gradle wrapper.
# ------------------------------------------------------------
set -e

# Determine the location of the wrapper and use it to locate the
# distribution. This mirrors the official Gradle wrapper script.
PRG="$0"

# Resolve symlinks
while [ -h "$PRG" ]; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done

PRGDIR=`dirname "$PRG"`
SCRIPT="$PRGDIR/gradle/wrapper/gradle-wrapper.jar"
CLASSPATH="$SCRIPT"

# Default JVM options, can be changed in GRADLE_OPTS env var.
DEFAULT_JVM_OPTS='"-Xmx64m"'

if [ -z "$JAVA_HOME" ] ; then
  java_exe="java"
else
  java_exe="$JAVA_HOME/bin/java"
fi

exec "$java_exe" $GRADLE_OPTS $DEFAULT_JVM_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
